Blog post: Camel Language Server including autocompletion from Kubernetes context
apache/camel-website pull request #1085
Opened 2023-10-27 10:43 UTC by Delawen

2023-10-27 11:34 UTC, apupier commented
build error:

```
[check:html     ]   1:9252  error  The autoplay attribute is not allowed on <video>  no-autoplay
[check:html     ]   1:9547  error  The autoplay attribute is not allowed on <video>  no-autoplay
```

2023-10-27 11:48 UTC, apupier requested changes
- the camel-featured.jpeg and the videos are cropping the completion list. As it is the main feature, i think it will provide a better view if it is more centered on it

2023-10-27 11:48 UTC, apupier commented on content/blog/2023/10/camel-language-server-kubernetes-context/index.md
> +Coming in the next VS Code Language support for Apache Camel, we are introducing a better context based autocompletion. We already had namespaces being auto completed when a related property was fill
it is already released :-) In Vs Code language Support 0.12.0

2023-10-27 11:48 UTC, apupier commented on content/blog/2023/10/camel-language-server-kubernetes-context/index.md
> +title: "VSCode Language Support Autocompletion from Kubernetes Context"
```suggestion
title: "VS Code Language Support Autocompletion from Kubernetes Context for secrets and configmaps"
```

there was already completion for namespace, so I think we need to be a bit more specific in the title.

VSCode --> VS Code

2023-10-27 11:48 UTC, apupier commented on content/blog/2023/10/camel-language-server-kubernetes-context/index.md
> +<video loop="true" autoplay="true" src="https://user-images.githubusercontent.com/726590/273884659-c03020ae-bd5b-4328-a57c-d8aa7750e79f.webm" controls="controls" muted="muted" ></video>
have you tried to build the site locally?
Last time I tried (several months if not years ago, the video were not working)

2023-10-27 11:48 UTC, apupier commented on content/blog/2023/10/camel-language-server-kubernetes-context/index.md
> +Coming in the next VS Code Language support for Apache Camel, we are introducing a better context based autocompletion. We already had namespaces being auto completed when a related property was fill
```suggestion
Coming in the next [VS Code Language support for Apache Camel](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-apache-camel), we are introducing a better context based autocompletion. We already had namespaces being auto completed when a related property was filled and there was a Kubernetes connection configured. 
```

2023-10-28 07:02 UTC, oscerd approved these changes

2024-02-26 10:20 UTC, oscerd commented
There is no point in leaving this open after 5 months. Closing.

2024-02-26 10:20 UTC, closed without merging