Add camel-karaf subproject
apache/camel-website pull request #1274
Opened 2024-12-23 06:48 UTC by jbonofre

2024-12-23 08:00 UTC, oscerd requested changes
[build:antora  ] [build:antora-perf] [06:57:58.403] FATAL (antora): Duplicate nav in 4.5.x@camel-karaf: modules/ROOT/nav.adoc

A part from that I'm fine with the PR

2024-12-28 06:02 UTC, jbonofre commented
Let me fix the nav. Thanks !

2025-01-02 08:50 UTC, squakez approved these changes

2025-01-05 07:39 UTC, jbonofre commented
@oscerd @squakez I fixed the issues on the nav and milestone. It's all good now.

2025-01-05 08:26 UTC, oscerd approved these changes

2025-01-05 08:26 UTC, merged