Camel debugger blog post
apache/camel-website pull request #737
Opened 2021-12-23 16:53 UTC by javaduke

2021-12-24 06:56 UTC, apupier commented on content/blog/2021/23/camelDebuggerForIntelliJ/index.md
> +- If you want to evaluate expressions in the [DataSonnet language](https://camel.apache.org/components/3.13.x/languages/datasonnet-language.html), add the following dependencies to your `pom.xml`:
links internal to the website needs to be relative

2021-12-24 06:56 UTC, apupier commented on content/blog/2021/23/camelDebuggerForIntelliJ/index.md
> +- If you want to evaluate expressions in the [DataSonnet language](https://camel.apache.org/components/3.13.x/languages/datasonnet-language.html), add the following dependencies to your `pom.xml`:
maybe better to point to LTS instead of 3.13.x version

2021-12-24 07:03 UTC, apupier commented on content/blog/2021/23/camelDebuggerForIntelliJ/index.md
> +- conditional breakpoints with Simple language predicates;
optional: for consistency, I think you should provide capital letter to start the bullet

2021-12-24 07:40 UTC, apupier requested changes
already a great article. Provided few required changes and some optional ideas of enhancements inlined.

Another required one: 
- the folder name is incorrect, it is in 2021/23 but it should be in 2021/12

Other suggestions:
- I think that providing a gif for basic use case would improve the wow effect
- A gif for each (most) of the main functionalities would help to grasp how awesome the added feature is

2021-12-24 07:40 UTC, apupier commented on content/blog/2021/23/camelDebuggerForIntelliJ/index.md
> +![](expressionEvaluator.png "Camel Debugger and Expression Evaluator")
```suggestion
![Camel Debugger and Expression Evaluator](./expressionEvaluator.png)
```

2021-12-24 07:40 UTC, apupier commented on content/blog/2021/23/camelDebuggerForIntelliJ/index.md
> +date: 2021-12-23T07:53:49-07:00
optional: for the date, it is possible to keep it simpler, and provide just `date: 2021-12-24`

2021-12-24 07:40 UTC, apupier commented on content/blog/2021/23/camelDebuggerForIntelliJ/index.md
> +We'd like to hear from you! Please be sure to submit your bug reports and enhancement requests to the [Camel IDEA Plugin issue tracker](https://github.com/camel-tooling/camel-idea-plugin/issues)!
optional: we can propose to vote for issues with a "debugger" label https://github.com/camel-tooling/camel-idea-plugin/labels/debugger

2021-12-24 08:28 UTC, oscerd approved these changes

2021-12-27 08:47 UTC, davsclaus commented
Can you update the date of the blog post to today

2021-12-27 13:37 UTC, javaduke commented
> Can you update the date of the blog post to today

Done.

2021-12-29 09:23 UTC, merged