New release vs code debug adapter0.2.0
apache/camel-website pull request #839
Opened 2022-05-03 14:17 UTC by apupier

easier to review and merge https://github.com/apache/camel-website/pull/838 before

2022-05-03 15:22 UTC, orpiske requested changes
Looking good. There's a few typos I highlighted.

2022-05-03 15:22 UTC, orpiske commented on content/blog/2022/05/vscode-extension-release-debug-0.2.0/index.md
> +There are several requirements to leverage the Debugger functionalities. In case, the debug adapter for Camel is not able to connect to the launched Camel application, an errro messaeg is now display
There's a typo. I believe you meant `error message` instead of `errro messaeg`.

2022-05-03 15:22 UTC, orpiske commented on content/blog/2022/05/vscode-extension-release-debug-0.2.0/index.md
> +Previously, I published a [blogpost](/blog/2022/04/start-camel-application-with-camel-textual-debug-in-vscode/) on how to configure tasks and launch configurations. New snippets are available on comp
Typo: "it" instead of "It".

2022-05-03 17:21 UTC, davsclaus approved these changes

2022-05-04 09:21 UTC, apupier commented
Thanks for the reviews.
The https://github.com/apache/camel-website/pull/838 was already merged.
Do you want to merge right away or do you want me to rebase my PR first?

2022-05-04 09:30 UTC, merged

2022-05-04 09:30 UTC, davsclaus commented
No, its okay we can squash and merge