feat: Camel K 1.10.0 announcement
apache/camel-website pull request #894
Opened 2022-09-05 15:42 UTC by squakez

FYI @tadayosi @claudio4j @christophd @essobedo @haanhvu @oscerd @halmakidon @astefanutti @orpiske @lburgazzoli @ammachado

2022-09-05 15:51 UTC, oscerd requested changes
Just one minor finding

2022-09-05 15:51 UTC, oscerd commented on content/blog/2022/09/camel-k-release-1-10/index.md
> +As usual, we have taken the opportunity to upgrade most of the dependencies we have. In particular we should mention we're now building Camel K with **Golang version 1.7**. Then, as we've mentioned e
1.17 is the correct version for golang

2022-09-05 16:24 UTC, orpiske approved these changes
Looking great, thanks!

2022-09-05 16:25 UTC, claudio4j approved these changes

2022-09-06 07:11 UTC, astefanutti approved these changes

2022-09-07 07:54 UTC, merged